/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
export interface UserResDtoOutput {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
}

export type UsersResDtoOutputItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type UsersResDtoOutput = UsersResDtoOutputItem[];

export type userControllerUserByIdResponseDefault = {
  data: UserResDtoOutput;
  status: number;
};
export type userControllerUserByIdResponseError =
  userControllerUserByIdResponseDefault & {
    headers: Headers;
  };

export type userControllerUserByIdResponse =
  userControllerUserByIdResponseError;

export const getUserControllerUserByIdUrl = (id: number) => {
  return `/users/${id}`;
};

export const userControllerUserById = async (
  id: number,
  options?: RequestInit,
): Promise<userControllerUserByIdResponse> => {
  const res = await fetch(getUserControllerUserByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerUserByIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as userControllerUserByIdResponse;
};

export type userControllerUsersResponseDefault = {
  data: UsersResDtoOutput;
  status: number;
};
export type userControllerUsersResponseError =
  userControllerUsersResponseDefault & {
    headers: Headers;
  };

export type userControllerUsersResponse = userControllerUsersResponseError;

export const getUserControllerUsersUrl = () => {
  return `/users`;
};

export const userControllerUsers = async (
  options?: RequestInit,
): Promise<userControllerUsersResponse> => {
  const res = await fetch(getUserControllerUsersUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerUsersResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as userControllerUsersResponse;
};
