/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
export interface UserResDtoOutput {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
}

export type UsersResDtoOutputRootItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export interface UsersResDtoOutput {
  root?: UsersResDtoOutputRootItem[];
}

export type appControllerUserByIdResponseDefault = {
  data: UserResDtoOutput;
  status: number;
};
export type appControllerUserByIdResponseError =
  appControllerUserByIdResponseDefault & {
    headers: Headers;
  };

export type appControllerUserByIdResponse = appControllerUserByIdResponseError;

export const getAppControllerUserByIdUrl = (id: number) => {
  return `/users/${id}`;
};

export const appControllerUserById = async (
  id: number,
  options?: RequestInit,
): Promise<appControllerUserByIdResponse> => {
  const res = await fetch(getAppControllerUserByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerUserByIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as appControllerUserByIdResponse;
};

export type appControllerUsersResponseDefault = {
  data: UsersResDtoOutput;
  status: number;
};
export type appControllerUsersResponseError =
  appControllerUsersResponseDefault & {
    headers: Headers;
  };

export type appControllerUsersResponse = appControllerUsersResponseError;

export const getAppControllerUsersUrl = () => {
  return `/users`;
};

export const appControllerUsers = async (
  options?: RequestInit,
): Promise<appControllerUsersResponse> => {
  const res = await fetch(getAppControllerUsersUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerUsersResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as appControllerUsersResponse;
};
