/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
import { customFetch } from "../fetcher";
export interface UserResDto {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
}

export interface UserResDtoOutput {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
}

export type UsersResDtoItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type UsersResDto = UsersResDtoItem[];

export type UsersResDtoOutputItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type UsersResDtoOutput = UsersResDtoOutputItem[];

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type userControllerUserByIdResponse200 = {
  data: UserResDto;
  status: 200;
};

export type userControllerUserByIdResponseDefault = {
  data: UserResDtoOutput;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type userControllerUserByIdResponseSuccess =
  userControllerUserByIdResponse200 & {
    headers: Headers;
  };
export type userControllerUserByIdResponseError =
  userControllerUserByIdResponseDefault & {
    headers: Headers;
  };

export type userControllerUserByIdResponse =
  | userControllerUserByIdResponseSuccess
  | userControllerUserByIdResponseError;

export const getUserControllerUserByIdUrl = (id: number) => {
  return `/users/${id}`;
};

export const userControllerUserById = async (
  id: number,
  options?: RequestInit,
): Promise<userControllerUserByIdResponse> => {
  return customFetch<userControllerUserByIdResponse>(
    getUserControllerUserByIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export type userControllerUsersResponse200 = {
  data: UsersResDto;
  status: 200;
};

export type userControllerUsersResponseDefault = {
  data: UsersResDtoOutput;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type userControllerUsersResponseSuccess =
  userControllerUsersResponse200 & {
    headers: Headers;
  };
export type userControllerUsersResponseError =
  userControllerUsersResponseDefault & {
    headers: Headers;
  };

export type userControllerUsersResponse =
  | userControllerUsersResponseSuccess
  | userControllerUsersResponseError;

export const getUserControllerUsersUrl = () => {
  return `/users`;
};

export const userControllerUsers = async (
  options?: RequestInit,
): Promise<userControllerUsersResponse> => {
  return customFetch<userControllerUsersResponse>(getUserControllerUsersUrl(), {
    ...options,
    method: "GET",
  });
};
