/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetch } from "../fetcher";
export interface UserResDto {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
}

export interface UserResDtoOutput {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
}

export type UsersResDtoItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type UsersResDto = UsersResDtoItem[];

export type UsersResDtoOutputItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type UsersResDtoOutput = UsersResDtoOutputItem[];

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type userControllerUserByIdResponse200 = {
  data: UserResDto;
  status: 200;
};

export type userControllerUserByIdResponseDefault = {
  data: UserResDtoOutput;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type userControllerUserByIdResponseSuccess =
  userControllerUserByIdResponse200 & {
    headers: Headers;
  };
export type userControllerUserByIdResponseError =
  userControllerUserByIdResponseDefault & {
    headers: Headers;
  };

export type userControllerUserByIdResponse =
  | userControllerUserByIdResponseSuccess
  | userControllerUserByIdResponseError;

export const getUserControllerUserByIdUrl = (id: number) => {
  return `/users/${id}`;
};

export const userControllerUserById = async (
  id: number,
  options?: RequestInit,
): Promise<userControllerUserByIdResponse> => {
  return customFetch<userControllerUserByIdResponse>(
    getUserControllerUserByIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getUserControllerUserByIdQueryKey = (id: number) => {
  return [`/users/${id}`] as const;
};

export const getUserControllerUserByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerUserById>>,
  TError = UserResDtoOutput,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerUserById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserControllerUserByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerUserById>>
  > = ({ signal }) => userControllerUserById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerUserById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerUserByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUserById>>
>;
export type UserControllerUserByIdQueryError = UserResDtoOutput;

export function useUserControllerUserById<
  TData = Awaited<ReturnType<typeof userControllerUserById>>,
  TError = UserResDtoOutput,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerUserById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerUserByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type userControllerUsersResponse200 = {
  data: UsersResDto[];
  status: 200;
};

export type userControllerUsersResponseDefault = {
  data: UsersResDtoOutput;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type userControllerUsersResponseSuccess =
  userControllerUsersResponse200 & {
    headers: Headers;
  };
export type userControllerUsersResponseError =
  userControllerUsersResponseDefault & {
    headers: Headers;
  };

export type userControllerUsersResponse =
  | userControllerUsersResponseSuccess
  | userControllerUsersResponseError;

export const getUserControllerUsersUrl = () => {
  return `/users`;
};

export const userControllerUsers = async (
  options?: RequestInit,
): Promise<userControllerUsersResponse> => {
  return customFetch<userControllerUsersResponse>(getUserControllerUsersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getUserControllerUsersQueryKey = () => {
  return [`/users`] as const;
};

export const getUserControllerUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerUsers>>,
  TError = UsersResDtoOutput,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof userControllerUsers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerUsersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerUsers>>
  > = ({ signal }) => userControllerUsers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUsers>>
>;
export type UserControllerUsersQueryError = UsersResDtoOutput;

export function useUserControllerUsers<
  TData = Awaited<ReturnType<typeof userControllerUsers>>,
  TError = UsersResDtoOutput,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof userControllerUsers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerUsersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
